---
title: "Critical Habitat Identification and ECAN Assessment"
author: "Supsup et al."
date: "06 January 2023"
output:
  html_document:
    df_print: paged
  pdf_document: default
indent: no
---
```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```
```{r, load require packages, results='hide'}
#install packages
list.of.packages <- c("raster", "terra", "sf", "tidyverse")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]

if(length(new.packages)) install.packages(new.packages, repos = "http://cran.us.r-project.org")

#load packages
library(terra)
library(raster)
library(sf)
```

**1. Load vegetation and sdm data**
```{r, load images}
#read data
veg <- rast("data/veg.tif")
sdm <- rast("data/sdm.tif")

#repoject data to utm
#data.crs <- "+proj=utm +zone=50 +ellps=WGS84 +datum=WGS84 +units=m +no_defs "
#veg.utm <- rast(projectRaster(veg, crs = data.crs))
#sdm.utm <- rast(projectRaster(sdm, crs = data.crs))

#view data
plot(veg, col = terrain.colors(255))
plot(sdm)
#convert data to polygon
#system.time( veg.poly <- as.polygons(veg.utm)) #time stamp

veg.poly <- as.polygons(veg)
sdm.poly <- as.polygons(sdm)

writeVector(veg.poly, "shapefiles/veg.poly.shp", overwrite = TRUE)
writeVector(sdm.poly, "shapefiles/sdm.poly.shp", overwrite = TRUE)
```

**2. Intersect vegetation and sdm data**
```{r, read shape}
#read data
veg.shp <- st_read("shapefiles/veg.poly.shp", quiet = TRUE)
sdm.shp <- st_read("shapefiles/sdm.poly.shp", quiet = TRUE)

#intersect vegetation and sdm data
sdm.veg.int <- intersect(veg.poly, sdm.poly)

#export as shapefile
writeVector(sdm.veg.int, "shapefiles/sdm.veg.shp", overwrite = TRUE)
```

**3. Identify important habitat**
```{r, important hab}
#read data
library(tidyverse)
ch <- st_read("shapefiles/sdm.veg.shp", quiet = TRUE)

#identify important habitat using the condition below

#CVT + <10 SPP = Not Important
#CVT + >10 SPP = Very Low Importance
#ESG + < 10 SPP = Low Importance 
#ESG + >10 SPP =  Moderate Importance 
#ASG/OGF + MGR + <10 SPP = High Importance
#ASG/OGF + MGR + >10 SPP = Highest Importance

ch.id <- mutate(ch, crithab = if_else(veg==3 & sdm<10, "Not Important", if_else(veg==3 & sdm>=10, "Very Low Importance", if_else(veg==2 & sdm<10, "Low Importance", if_else(veg==2 & sdm>=10, "Moderate Importance", if_else(veg==1 & sdm<10, "High Importance", if_else(veg==1 & sdm>=10, "Highest Importance", if_else(veg==4 & sdm<10, "High Importance", if_else(veg==4 & sdm>=10, "Highest Importance", "Not Data")))))))))

p <- vect(ch.id)

#plot
plot(p, "crithab", lwd = 0.01, main = "Critical habitat", mar=c(3.1, 3.1, 2.1, 9.1))

#export critical habitat
st_write(ch, "shapefiles/crithab.shp", driver="ESRI Shapefile")
```

**4. Identify mismatch between identified critical habitat and ecan core zone**
```{r, identify mismatch}
library(units)
library(lwgeom)
library(smoothr)
library(rgdal)

#read data
ih.s <- readOGR(dsn = "shapefiles/", layer = "impthab")
#get important habitat with highest importance
high <- subset(ih.s, impthab == 'Highest Importance')
#drop areas < 100m2
high.dropped <- drop_crumbs(high, set_units(0.1, km^2))
#export
writeOGR(high.dropped, "shapefiles/", "high", driver="ESRI Shapefile")

#read critical habitat
ch <- st_read("shapefiles/high.shp", quiet = TRUE)
#merge fragmented polygons
ch.u <- ch %>% group_by(impthab) %>% summarise(geometry = sf::st_union(geometry)) %>% ungroup()
ch.val <- st_make_valid(ch.u)
#fill holes
ch.filled <- fill_holes(ch.val, set_units(0.1, km^2))

#read ecan core zone
core <- st_read("shapefiles/ecan_core.shp", quiet = TRUE)

#ensure that data crs is uniform
st_crs(ch.filled) <- 4326
st_crs(core) <- 4326

#install_github("a-benini/sfhelpers")
library(sfhelpers) 

#identify mismatch by getting the difference between the core zone and critical habitat
#condition: Highest Importance + Core Zone = "Matched, with ch and core zone"; Highest Importance + No Core Zone = "Mismatched, with ch but no protection"; No Important Habitat + Core Zone = "Mismatched, with protection but no ch"

ch.core <- st_or(ch.filled, core)#use union function similar to QGIS
#replace NAs with 0
ch.core.r.na <- ch.core %>% replace(is.na(.), 0)

#apply condition
ch.core.m <- mutate(ch.core.r.na, diff = if_else(impthab %in% "Highest Importance" & ECAN_CODE==1, "Matched, with CH and CZ", if_else(impthab %in% "Highest Importance" & ECAN_CODE==0, "Mismatched, with CH but no CZ", if_else(impthab==0 & ECAN_CODE==1, "Mismatched, with CZ but no CH", "Not data"))))

#plot
p.ch <- vect(ch.core.m)
plot(p.ch, "diff", lwd = 0.01, main = "CH and ECAN core zone assessment", mar=c(3.1, 3.1, 2.1, 12.1))

#export critical habitat and ecan assessment
st_write(ch.core.m, "shapefiles/ch.core.m.shp", driver="ESRI Shapefile")
```
